version: '3.9'

services:
  # NodeJS application
  api:
    build: .

  # Reverse Proxy
  ngnix:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - 3000:3000